### ISSUE TITLE
optionally format output

### ISSUE THREAD

**Issue by elidoran** [jonschlinkert/benchmarked#8]
At [this line](https://github.com/jonschlinkert/benchmarked/blob/master/index.js#L294) it outputs the result for the current benchmark.

I'd like to specify a function which accepts that object and returns a formatted string.

Before I start I'm wondering, what do you think?

I'm thinking something like:

```javascript
var suite = require('benchmarked')({
  cwd: 'benchmark',
  fixtures: 'my-fixtures/*.txt',
  code: 'my-functions/*.js',
  format: function (benchmark) {
    // like current implementation:
    return '  ' + benchmark
  }
})

suite.run()
```

It would provide the option on down the calls to the `addSuite()` function where it would be used inside `cursor.write(format(event.target))`, or, the default format would be used.

**Comment by jonschlinkert** [comment]
Great idea! Interested in doing a pr?

**Comment by elidoran** [comment]
Yes. I went ahead and implemented it already. :)

I ended up adding the default `format` function to `this.options` in the `defaults()` function and then using `cursor.write(opts.format(event.target))`.

Works great. I used it to color and pad the results.

I'll make the PR now.

Thank you.

**Comment by elidoran** [comment]
All set. It's in #9
